apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-html
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-html
  template:
    metadata:
      labels:
        app: hello-world-html
    spec:
      containers:
      - name: hello-world-html
        image: hello-world-html:latest
        imagePullPolicy: Never  
        ports:
        - containerPort: 80
